// Deduplicated tools/frameworks from portfolio sections, projects, and CV.
export const PROFICIENT_TOOLS = [
  "TypeScript",
  "JavaScript",
  "Node.js",
  "NestJS",
  "Express",
  "React",
  "Next.js",
  "Vue.js",
  "Tailwind CSS",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "Sequelize",
  "Drizzle",
  "Supabase",
  "Stripe",
  "Paystack",
  "Docker",
  "Jest",
  "Swagger",
  "Firebase",
  "MetaMap",
  "Clerk",
  "Sentry",
  "Twilio",
  "Zod",
  "GraphQL",
  "Google Cloud",
  "Render",
  "Termii",
  "Nodemailer",
  "Solana",
];

export const PROFICIENT_TOOLS_COUNT = PROFICIENT_TOOLS.length;
